### ISSUE TITLE
Game pacing & length

### ISSUE THREAD

**Issue by bjoernross** [valentjn/santa-racer-rust#3]
The original games only takes 2:30 to complete and you can race to the finish with a little over 50 seconds left if you want. This seems to be because the game scrolls faster when you have the right arrow key pressed. (When you just move the sleigh as far right as possible but don't keep the key pressed, you reach the finish with around 7 seconds left.)

I've been fiddling with the code and I can obviously set `game_duration` to 150 seconds but the level is too long to finish it in that time and the speed of the sleigh does not depend on whether the key is pressed.

Again, is this a bug or a design decision? :-)

**Comment by valentjn** [comment]
You probably don't know the [cheat codes](https://web.archive.org/web/20020806113214/http://bildschirmschoner.de/savers/content/DContent0238.html). If you typed in one of those (I think it was `Langlauf`), the game would switch to a much longer level, which is definitely more fun for me than the short one. (And no, I'm not planning to implement the cheat codes.)

**Comment by bjoernross** [comment]
Haha, I had no idea that these even existed! Thanks. I've worked out how to move the finish (the 76 in `levelNpcMap.txt`) so I was able to tweak the game myself to be shorter :-)
